import torch
import numpy as np
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import List, Tuple

from src.agent.fcn_agent import MinesweeperActorCritic, FCNAgent

app = FastAPI(
    title="Minesweeper RL Inference API",
    description="Local endpoint serving the Actor-Critic model weights for GUI interaction.",
    version="1.0.0"
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = None
agent = None

@app.on_event("startup")
def load_model_weights():
    global model, agent
    try:
        model = MinesweeperActorCritic().to(device)
        # Load weights generated by train.py
        model.load_state_dict(torch.load("a2c_minesweeper_agent.pt", map_location=device))
        model.eval()
        agent = FCNAgent(model=model, device=device)
        print(f"Production model successfully loaded on {device}")
    except FileNotFoundError:
        print("Warning: a2c_minesweeper_agent.pt not found. Initializing with random weights.")
        model = MinesweeperActorCritic().to(device)
        model.eval()
        agent = FCNAgent(model=model, device=device)

class InferencePayload(BaseModel):
    board: List[List[int]]
    valid_actions: List[Tuple[int, int]]

@app.post("/predict")
def predict(payload: InferencePayload):
    if agent is None:
        raise HTTPException(status_code=503, detail="Model network is not initialized.")
    
    try:
        # Convert incoming JSON list to NumPy array
        obs = np.array(payload.board, dtype=np.int8)
        
        # Execute action selection
        action = agent.select_action(obs, payload.valid_actions)
        
        return {
            "row": int(action[0]),
            "col": int(action[1]),
            "status": "success"
        }
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))

@app.get("/health")
def health_check():
    return {
        "status": "healthy",
        "device": str(device),
        "model_file_found": model is not None
    }   